# .travis.yml
language: node_js
node_js:
   - "0.10"
#
#services:
#  - couchdb
#  - neo4j
before_script:
- npm install -g jasmine-node
- npm install -g request
#  - curl -X PUT localhost:5984/users
#  - curl -X PUT localhost:5984/groups
#  - curl -X PUT localhost:5984/business
#  - curl -X PUT localhost:5984/offers